var tomicaDB = [
  /* Regular Models */
  {id: 0, rev: 1, mod: 0, name: 'Tomica Wrapping Bus', isLimited: false},

  {id: 1, rev: 3, mod: 0, name: 'Hino Grandview Bus', isLimited: false},
  {id: 1, rev: 4, mod: 0, name: 'Mitsubishi Fuso Aero Queen', isLimited: false},
  {id: 1, rev: 5, mod: 0, name: 'Mitsubishi Fuso Aero Queen', isLimited: false},

  {id: 2, rev: 4, mod: 0, name: 'Mitsubishi Fuso Canter Tow Truck (Wrecker)', isLimited: false},
  {id: 2, rev: 5, mod: 0, name: 'Hanta Asphalt Paver F1741WZ', isLimited: false},

  {id: 3, rev: 4, mod: 0, name: 'Hiace Delivery Van', isLimited: false},
  {id: 3, rev: 5, mod: 0, name: 'Toyota Mega Cruiser Patrol Car', isLimited: false},
  {id: 3, rev: 6, mod: 0, name: 'Animal Transporter (Black Bear)', isLimited: true},
  {id: 3, rev: 6, mod: 1, name: 'Animal Transporter (Pandas)', isLimited: false},

  {id: 4, rev: 5, mod: 0, name: 'Mazda Familia', isLimited: false},
  {id: 4, rev: 6, mod: 0, name: 'Honda Police Bike', isLimited: false},
  {id: 4, rev: 7, mod: 0, name: 'Honda VFR Police Bike', isLimited: false},

  {id: 5, rev: 3, mod: 0, name: 'Toyota Soarer', isLimited: false},
  {id: 5, rev: 4, mod: 0, name: 'Toyota Land Cruiser', isLimited: false},
  {id: 5, rev: 5, mod: 0, name: 'Chevrolet Corvette Z06', isLimited: true},
  {id: 5, rev: 5, mod: 1, name: 'Chevrolet Corvette Z06', isLimited: false},

  {id: 6, rev: 4, mod: 0, name: 'Silvia Coupe', isLimited: false},
  {id: 6, rev: 5, mod: 0, name: 'Nissan Silvia', isLimited: false},
  {id: 6, rev: 6, mod: 0, name: 'Honda Super Cub', isLimited: false},
  {id: 6, rev: 7, mod: 0, name: 'Honda Little Cub', isLimited: false},
  {id: 6, rev: 8, mod: 0, name: 'Isuzu Elf', isLimited: false},
  {id: 6, rev: 9, mod: 0, name: 'Audi R8', isLimited: true},
  {id: 6, rev: 9, mod: 1, name: 'Audi R8', isLimited: false},

  {id: 7, rev: 3, mod: 0, name: 'Refergerator Car', isLimited: false},
  {id: 7, rev: 4, mod: 0, name: 'Mitsubishi Super Great Truck', isLimited: false},
  {id: 7, rev: 5, mod: 0, name: 'Alsok Security Transport Car', isLimited: false},
  {id: 7, rev: 6, mod: 0, name: 'Subaru Impreza WRX STI 4 door', isLimited: false},
  {id: 7, rev: 7, mod: 0, name: 'Subaru Impreza WRX STI 4 door Group R4', isLimited: false},

  {id: 8, rev: 3, mod: 0, name: 'Cedric Taxi', isLimited: false},
  {id: 8, rev: 4, mod: 0, name: 'Nissan Skyline', isLimited: false},
  {id: 8, rev: 5, mod: 0, name: 'Nissan Pino', isLimited: false},
  {id: 8, rev: 6, mod: 0, name: 'Nissan Fuga', isLimited: false},
  {id: 8, rev: 7, mod: 0, name: 'Nissan Cima', isLimited: false},
  {id: 8, rev: 8, mod: 0, name: 'Suzuki Alto', isLimited: true},
  {id: 8, rev: 8, mod: 1, name: 'Suzuki Alto', isLimited: false},

  {id: 9, rev: 4, mod: 0, name: 'Komatsu Power Shovel PC 200 Galeo', isLimited: false},
  {id: 9, rev: 5, mod: 0, name: 'Komatsu Excavator PC 200-10', isLimited: false},

  {id: 10, rev: 4, mod: 0, name: 'Subaru Sambar Bakery', isLimited: false},
  {id: 10, rev: 5, mod: 0, name: 'Subaru Samber Bakery', isLimited: false},
  {id: 10, rev: 6, mod: 0, name: 'Lotus Exige R-GT', isLimited: true},
  {id: 10, rev: 6, mod: 1, name: 'Lotus Exige R-GT', isLimited: false},

  {id: 11, rev: 3, mod: 0, name: 'Subaru Legacy', isLimited: false},
  {id: 11, rev: 4, mod: 0, name: 'Subaru Impreza WRX STI', isLimited: false},
  {id: 11, rev: 5, mod: 0, name: 'SRT Viper GTS', isLimited: true},
  {id: 11, rev: 5, mod: 1, name: 'SRT Viper GTS', isLimited: false},

  {id: 12, rev: 4, mod: 0, name: 'Nissan Paramedic', isLimited: false},
  {id: 12, rev: 5, mod: 0, name: 'Nissan March', isLimited: false},
  {id: 12, rev: 6, mod: 0, name: 'Nissan Porte', isLimited: false},
  {id: 12, rev: 7, mod: 0, name: 'Toyota Alphard', isLimited: true},
  {id: 12, rev: 7, mod: 1, name: 'Toyota Alphard', isLimited: false},

  {id: 13, rev: 5, mod: 0, name: 'Cedric 4Door Hardtop', isLimited: false},
  {id: 13, rev: 6, mod: 0, name: 'Cedric', isLimited: false},
  {id: 13, rev: 7, mod: 0, name: 'Nissan Cedric', isLimited: false},
  {id: 13, rev: 8, mod: 0, name: 'Rescue Work Car', isLimited: false},
  {id: 13, rev: 9, mod: 0, name: 'Morita Airport Crash Tender MAF-125A', isLimited: false},
  {id: 13, rev: 10, mod: 0, name: 'Mitsubishi Fuso Canter', isLimited: false},
  {id: 13, rev: 11, mod: 0, name: 'Lexus RC-F', isLimited: true},
  {id: 13, rev: 11, mod: 1, name: 'Lexus RC-F', isLimited: false},

  {id: 14, rev: 3, mod: 0, name: 'Isuzu Elf Carcarrier', isLimited: false},
  {id: 14, rev: 4, mod: 0, name: 'Super Great Car Carrier', isLimited: false},
  {id: 14, rev: 5, mod: 0, name: 'Komatsu Anti-personnel Landmine Demining Eqt D 85 MS', isLimited: false},
  {id: 14, rev: 6, mod: 0, name: 'Formula Renault 3.5', isLimited: true},
  {id: 14, rev: 6, mod: 1, name: 'Formula Renault 3.5', isLimited: false},

  {id: 15, rev: 4, mod: 0, name: 'Fairlady Z', isLimited: false},
  {id: 15, rev: 5, mod: 0, name: 'Nissan Fairlady Z 300ZX', isLimited: false},
  {id: 15, rev: 6, mod: 0, name: 'Daihatsu Copen', isLimited: false},
  {id: 15, rev: 7, mod: 0, name: 'Hummer H2', isLimited: false},

  {id: 16, rev: 3, mod: 0, name: 'Toyota Corolla Spacio', isLimited: false},
  {id: 16, rev: 4, mod: 0, name: 'Mazda Atenza', isLimited: false},
  {id: 16, rev: 5, mod: 0, name: 'Suzuki Swift Sport Rallycup Car', isLimited: false},
  {id: 16, rev: 6, mod: 0, name: 'Isuzu Gala JR Bus Tohoku', isLimited: true},
  {id: 16, rev: 6, mod: 1, name: 'Isuzu Gala JR Bus Tohoku', isLimited: false},

  {id: 17, rev: 5, mod: 0, name: 'Civic 3000R', isLimited: false},
  {id: 17, rev: 6, mod: 0, name: 'Toyota Celsior', isLimited: false},
  {id: 17, rev: 7, mod: 0, name: 'Toyota Celsior', isLimited: false},
  {id: 17, rev: 8, mod: 0, name: 'Nissan Cube', isLimited: false},
  {id: 17, rev: 9, mod: 0, name: 'Nissan March Police Car', isLimited: false},

  {id: 18, rev: 5, mod: 0, name: 'Subaru Legacy Touring Wagon', isLimited: false},
  {id: 18, rev: 6, mod: 0, name: 'Nissan Wingroad', isLimited: true},
  {id: 18, rev: 6, mod: 1, name: 'Nissan Wingroad', isLimited: false},
  {id: 18, rev: 7, mod: 0, name: 'Jeep Wrangler', isLimited: false},
  {id: 18, rev: 8, mod: 0, name: 'Large Size Blower Truck', isLimited: false},
  {id: 18, rev: 9, mod: 0, name: 'Nissan NV350 Caravan Ambulance', isLimited: false},

  {id: 19, rev: 3, mod: 0, name: 'Bulk Trailer', isLimited: false},
  {id: 19, rev: 4, mod: 0, name: 'Mitsubishi Fuso Wing Body Truck', isLimited: false},
  {id: 19, rev: 5, mod: 0, name: 'Suzuki Alto', isLimited: false},
  {id: 19, rev: 6, mod: 0, name: 'Daihatsu Mira', isLimited: false},
  {id: 19, rev: 7, mod: 0, name: 'Chevrolet Camaro', isLimited: false},

  {id: 20, rev: 5, mod: 0, name: 'Nissan Skyline', isLimited: false},
  {id: 20, rev: 6, mod: 0, name: 'Nissan Skyline GTR', isLimited: false},
  {id: 20, rev: 7, mod: 0, name: 'Nissan Skyline GT-R (R 33)', isLimited: false},
  {id: 20, rev: 8, mod: 0, name: 'Nissan Skyline GT-R (R 34)', isLimited: false},
  {id: 20, rev: 9, mod: 0, name: 'Daihatsu Move Custom', isLimited: true},
  {id: 20, rev: 9, mod: 1, name: 'Daihatsu Move Custom', isLimited: false},
  {id: 20, rev: 10, mod: 0, name: 'Honda Insight', isLimited: false},
  {id: 20, rev: 11, mod: 0, name: 'Honda N Box', isLimited: false},

  {id: 21, rev: 5, mod: 0, name: 'Honda Stepwgn', isLimited: false},
  {id: 21, rev: 6, mod: 0, name: 'Honda STEP WGN', isLimited: false},
  {id: 21, rev: 7, mod: 0, name: 'Honda STEP WGN', isLimited: false},
  {id: 21, rev: 8, mod: 0, name: 'Nissan X-Trail', isLimited: false},

  {id: 22, rev: 4, mod: 0, name: 'Nissan Diesel Aerial Ladder Fire Truck', isLimited: false},
  {id: 22, rev: 5, mod: 0, name: 'Nissan Note', isLimited: false},
  {id: 22, rev: 6, mod: 0, name: 'Mercedes Benz Unimog', isLimited: true},
  {id: 22, rev: 6, mod: 1, name: 'Mercedes Benz Unimog', isLimited: false},

  {id: 23, rev: 4, mod: 0, name: 'Mitsubishi Fuso Covered Truck', isLimited: false},
  {id: 23, rev: 5, mod: 0, name: 'Mazda Bongo Friendee', isLimited: false},
  {id: 23, rev: 6, mod: 0, name: 'Nissan Skyline Safety Car', isLimited: false},
  {id: 23, rev: 7, mod: 0, name: 'Toyota Probox Voluntary Security Police Car', isLimited: false},
  {id: 23, rev: 8, mod: 0, name: 'Mitsubishi RVR', isLimited: false},
  {id: 23, rev: 9, mod: 0, name: 'Mitsubishi Mirage', isLimited: false},

  {id: 24, rev: 4, mod: 0, name: 'MR2 (Prototype)', isLimited: false},
  {id: 24, rev: 5, mod: 0, name: 'Toyota RAV4', isLimited: false},
  {id: 24, rev: 6, mod: 0, name: 'Toyota New Soarer', isLimited: false},
  {id: 24, rev: 7, mod: 0, name: 'Komatsu Motor Grader', isLimited: false},
  {id: 24, rev: 8, mod: 0, name: 'Kawasaki Helicopter "BR 117 C-2"', isLimited: false},

  {id: 25, rev: 3, mod: 0, name: 'Mitsubishi Jeep Bigfoot', isLimited: false},
  {id: 25, rev: 4, mod: 0, name: 'Mitsuoka Le-Seyde', isLimited: false},
  {id: 25, rev: 5, mod: 0, name: 'Mitsuoka Orochi', isLimited: false},

  {id: 26, rev: 5, mod: 0, name: 'Exploratory Bus', isLimited: false},
  {id: 26, rev: 6, mod: 0, name: 'Shimajiro Car', isLimited: false},
  {id: 26, rev: 7, mod: 0, name: 'Tokai University Solar Car Tokai Challenger', isLimited: false},
  {id: 26, rev: 8, mod: 0, name: 'Mazda Roadster', isLimited: true},
  {id: 26, rev: 8, mod: 1, name: 'Mazda Roadster', isLimited: false},

  {id: 27, rev: 5, mod: 0, name: 'Isuzu Hipac Van', isLimited: false},
  {id: 27, rev: 6, mod: 0, name: 'Toyota Will Vi', isLimited: false},
  {id: 27, rev: 7, mod: 0, name: 'Mitsubishi Grandis', isLimited: false},
  {id: 27, rev: 8, mod: 0, name: 'Toyota Corolla Axio', isLimited: false},
  {id: 27, rev: 9, mod: 0, name: 'Nissan Juke', isLimited: false},
  {id: 27, rev: 10, mod: 0, name: 'Nissan NV350 Caravan Fire Chief Car', isLimited: false},

  {id: 28, rev: 5, mod: 0, name: 'Crown Taxi', isLimited: false},
  {id: 28, rev: 6, mod: 0, name: 'High-way Public Co.', isLimited: false},
  {id: 28, rev: 7, mod: 0, name: 'Honda Elysion', isLimited: false},
  {id: 28, rev: 8, mod: 0, name: 'Toyota iQ', isLimited: false},
  {id: 28, rev: 9, mod: 0, name: 'John Deere Combine 6970 STS', isLimited: false},
  {id: 28, rev: 10, mod: 0, name: 'Yanmar Combine YH590', isLimited: false},

  {id: 29, rev: 3, mod: 0, name: 'Mitsubishi Fuso Canter Sakai Moving Service', isLimited: false},

  {id: 30, rev: 4, mod: 0, name: 'Quint Integra', isLimited: false},
  {id: 30, rev: 5, mod: 0, name: 'Mitsubishi Pajero Metal Top', isLimited: false},
  {id: 30, rev: 6, mod: 0, name: 'Mitsubishi Pajero', isLimited: false},
  {id: 30, rev: 7, mod: 0, name: 'Mitsubishi Fuso Aero Star Route Bus', isLimited: false},
  {id: 30, rev: 8, mod: 0, name: 'Dinosaur Carrier', isLimited: false},
  {id: 30, rev: 9, mod: 0, name: 'Hina Ranger Heavy Construction Machinery Transporter', isLimited: true},
  {id: 30, rev: 9, mod: 1, name: 'Hina Ranger Heavy Construction Machinery Transporter', isLimited: false},

  {id: 31, rev: 3, mod: 0, name: 'Subaru Sambar High Roof Panel Van', isLimited: false},
  {id: 31, rev: 4, mod: 0, name: 'Nissan Primera', isLimited: false},
  {id: 31, rev: 5, mod: 0, name: 'Nissan Cima', isLimited: false},
  {id: 31, rev: 6, mod: 0, name: 'Nissan Diesel Quon', isLimited: false},
  {id: 31, rev: 7, mod: 0, name: 'UD Trucks Condor', isLimited: false},
  {id: 31, rev: 8, mod: 0, name: 'Toyota FJ Cruiser Patrol Car', isLimited: false},

  {id: 32, rev: 5, mod: 0, name: 'Elf Powar Container', isLimited: false},
  {id: 32, rev: 6, mod: 0, name: 'Nissan Gloria', isLimited: false},
  {id: 32, rev: 7, mod: 0, name: 'Toyota Crown', isLimited: false},
  {id: 32, rev: 8, mod: 0, name: 'Toyota Crown', isLimited: false},
  {id: 32, rev: 9, mod: 0, name: 'Daihatsu Move', isLimited: true},
  {id: 32, rev: 9, mod: 1, name: 'Daihatsu Move', isLimited: false},
  {id: 32, rev: 10, mod: 0, name: 'Ministry of Land Lighting Vehicle', isLimited: false},

  {id: 33, rev: 5, mod: 0, name: 'Toyota Celica', isLimited: false},
  {id: 33, rev: 6, mod: 0, name: 'Toyota Supra', isLimited: false},
  {id: 33, rev: 7, mod: 0, name: 'Toyota Vitz', isLimited: true},
  {id: 33, rev: 7, mod: 1, name: 'Toyota Vitz', isLimited: false},
  {id: 33, rev: 8, mod: 0, name: 'Daihatsu Move Conte', isLimited: false},
  {id: 33, rev: 9, mod: 0, name: 'Volkswagen The Beetle', isLimited: true},
  {id: 33, rev: 9, mod: 1, name: 'Volkswagen The Beetle', isLimited: false},

  {id: 34, rev: 4, mod: 0, name: 'Bluebird Wagon', isLimited: false},
  {id: 34, rev: 5, mod: 0, name: 'Mazda 787B', isLimited: false},
  {id: 34, rev: 6, mod: 0, name: 'Mitsubishi Lancer Evolution VII GT-A', isLimited: false},
  {id: 34, rev: 7, mod: 0, name: 'Mitsubishi Delica D:5', isLimited: false},
  {id: 34, rev: 8, mod: 0, name: 'Komatsu Wheeled Excavator PW200', isLimited: false},
  {id: 34, rev: 9, mod: 0, name: 'Alsok Cash Transport Truck', isLimited: false},

  {id: 35, rev: 3, mod: 0, name: 'Mitsubishi Pajero Bigfoot', isLimited: false},
  {id: 35, rev: 4, mod: 0, name: 'Nissan March', isLimited: false},
  {id: 35, rev: 5, mod: 0, name: 'Subaru Samber Noodle Truck', isLimited: false},
  {id: 35, rev: 6, mod: 0, name: 'Honda CR-Z Safety Car', isLimited: false},
  {id: 35, rev: 7, mod: 0, name: 'Toyota Noah', isLimited: false},

  {id: 36, rev: 3, mod: 0, name: 'Hiace Ambulance', isLimited: false},
  {id: 36, rev: 4, mod: 0, name: 'Toyota Majesta Patrol Car', isLimited: false},
  {id: 36, rev: 5, mod: 0, name: 'Toyota Probox Highway Public Co. Patrol Car', isLimited: false},
  {id: 36, rev: 6, mod: 0, name: 'Nexco Self Run Type Mark Car', isLimited: false},
  {id: 36, rev: 7, mod: 0, name: 'Suzuki Swift', isLimited: false},
  {id: 36, rev: 8, mod: 0, name: 'Thomasland Express', isLimited: false},

  {id: 37, rev: 4, mod: 0, name: 'Coca-Cola Event Car', isLimited: false},
  {id: 37, rev: 5, mod: 0, name: 'Coca-Cola Event Car', isLimited: false},
  {id: 37, rev: 6, mod: 0, name: 'Hino Dutro Truck Crane', isLimited: false},

  {id: 38, rev: 5, mod: 0, name: 'Elf Skymaster', isLimited: false},
  {id: 38, rev: 6, mod: 0, name: 'Pocket Monsters Bus', isLimited: false},
  {id: 38, rev: 7, mod: 0, name: 'Mobile Rescue Bus', isLimited: false},
  {id: 38, rev: 8, mod: 0, name: 'Toyota Auto Body Coms', isLimited: false},

  {id: 39, rev: 4, mod: 0, name: 'Lift-Magnet Power Shovel', isLimited: false},
  {id: 39, rev: 5, mod: 0, name: 'Mitsubishi Lancer Evolution X British Police Type', isLimited: false},

  {id: 40, rev: 2, mod: 0, name: 'Skyline GTR Racing (JECS)', isLimited: false},
  {id: 40, rev: 3, mod: 0, name: 'Skyline Racing (UNICIA JECS)', isLimited: false},
  {id: 40, rev: 4, mod: 0, name: 'Skyline Racing (R33)', isLimited: false},
  {id: 40, rev: 5, mod: 0, name: 'Skyline Racing (R34)', isLimited: false},
  {id: 40, rev: 6, mod: 0, name: 'Mitsuoka Viewt', isLimited: false},
  {id: 40, rev: 7, mod: 0, name: 'Nissan Fairlady Z 40th Anniversary', isLimited: false},
  {id: 40, rev: 8, mod: 0, name: 'Nissan Fairlady Z Nismo', isLimited: true},
  {id: 40, rev: 8, mod: 1, name: 'Nissan Fairlady Z Nismo', isLimited: false},

  {id: 41, rev: 4, mod: 0, name: 'Isuzu Super Hi-Deckerbus', isLimited: false},
  {id: 41, rev: 5, mod: 0, name: 'Morita Fire Engine Type CD-I', isLimited: false},

  {id: 42, rev: 2, mod: 0, name: 'Honda CB 750 F', isLimited: false},
  {id: 42, rev: 3, mod: 0, name: 'Satellite Relay Truck', isLimited: false},
  {id: 42, rev: 4, mod: 0, name: 'Caterpillar Bulldozer', isLimited: false},
  {id: 42, rev: 5, mod: 0, name: 'Hato Bus', isLimited: false},
  {id: 42, rev: 6, mod: 0, name: 'Hato Bus', isLimited: true},
  {id: 42, rev: 6, mod: 1, name: 'Hato Bus', isLimited: false},

  {id: 43, rev: 2, mod: 0, name: 'Nissan Diesel Crane Truck', isLimited: false},
  {id: 43, rev: 3, mod: 0, name: 'Mini Cooper', isLimited: false},

  {id: 44, rev: 4, mod: 0, name: 'Fairlady Z Patrol Car', isLimited: false},
  {id: 44, rev: 5, mod: 0, name: 'Fairlady Z 300ZX Patrol Car', isLimited: false},
  {id: 44, rev: 6, mod: 0, name: 'Mazda RX-8 Patrol Car', isLimited: false},
  {id: 44, rev: 7, mod: 0, name: 'Renault Megane RS', isLimited: true},
  {id: 44, rev: 7, mod: 1, name: 'Renault Megane RS', isLimited: false},
  {id: 44, rev: 8, mod: 0, name: 'Megane Renault Sports Gendarmerie', isLimited: false},

  {id: 45, rev: 3, mod: 0, name: 'Suzuki Carry Chinese Noodle Vendor', isLimited: false},
  {id: 45, rev: 4, mod: 0, name: 'Toyota Dyna Refuse Truck', isLimited: false},

  {id: 46, rev: 3, mod: 0, name: 'Celica Rally', isLimited: false},
  {id: 46, rev: 4, mod: 0, name: 'Honda Odyssey', isLimited: false},
  {id: 46, rev: 5, mod: 0, name: 'Honda Odyssey', isLimited: false},
  {id: 46, rev: 6, mod: 0, name: 'Honda Odyssey', isLimited: false},
  {id: 46, rev: 7, mod: 0, name: 'Honda Odyssey', isLimited: false},
  {id: 46, rev: 8, mod: 0, name: 'Toyota 86', isLimited: true},
  {id: 46, rev: 8, mod: 1, name: 'Toyota 86', isLimited: false},
  {id: 46, rev: 9, mod: 0, name: 'Dahatsu Cast', isLimited: false},

  {id: 47, rev: 5, mod: 0, name: 'Animal Carrier (Penguin)', isLimited: false},
  {id: 47, rev: 6, mod: 0, name: 'Nichijo Manufacturing Rotary Snowplow HTR 265', isLimited: false},

  {id: 48, rev: 5, mod: 0, name: 'Isuzu Elf Snowplow', isLimited: false},
  {id: 48, rev: 6, mod: 0, name: 'SL Type Kinder Garden Bus', isLimited: false},
  {id: 48, rev: 7, mod: 0, name: 'Toyota Hiace Multi-Purpose Car', isLimited: false},
  {id: 48, rev: 8, mod: 0, name: 'Toyota Vellfire', isLimited: false},
  {id: 48, rev: 9, mod: 0, name: 'Suzuki Alto Police Car', isLimited: false},

  {id: 48, rev: 5, mod: 0, name: 'March 85G', isLimited: false},
  {id: 48, rev: 6, mod: 0, name: 'Amusment Park Shuttle Bus', isLimited: false},
  {id: 49, rev: 7, mod: 0, name: 'Yamazaki Delivery Truck', isLimited: false},
  {id: 49, rev: 8, mod: 0, name: 'Yamazaki Delivery Truck', isLimited: false},

  {id: 50, rev: 4, mod: 0, name: 'Savanna RX-7', isLimited: false},
  {id: 50, rev: 5, mod: 0, name: 'Toyota Ipsum', isLimited: false},
  {id: 50, rev: 6, mod: 0, name: 'Nissan Fairlady Z Racing Type', isLimited: false},
  {id: 50, rev: 7, mod: 0, name: 'Nissan GT-R Racing Car', isLimited: false},
  {id: 50, rev: 8, mod: 0, name: 'Hasemi Tomica Ebbro GT-R 2009 Sepang Spec', isLimited: false},
  {id: 50, rev: 9, mod: 0, name: 'Lotus Exige S', isLimited: false},
  {id: 50, rev: 10, mod: 0, name: 'Ford Focus RS', isLimited: true},
  {id: 50, rev: 10, mod: 1, name: 'Ford Focus RS500', isLimited: false},

  {id: 51, rev: 3, mod: 0, name: 'Nissan Bluebird', isLimited: false},
  {id: 51, rev: 4, mod: 0, name: 'Nissan Paramedic Ambulance', isLimited: false},
  {id: 51, rev: 5, mod: 0, name: 'Toyota Crown Taxi', isLimited: false},
  {id: 51, rev: 6, mod: 0, name: 'Toyota Crown Comfort Taxi', isLimited: false},

  {id: 52, rev: 2, mod: 0, name: 'Hino Dolphin Dumptruck', isLimited: false},
  {id: 52, rev: 3, mod: 0, name: 'Subaru Impreza Unmarked Police Car', isLimited: false},
  {id: 52, rev: 4, mod: 0, name: 'Yanmar Tractor Ecotra EG 300 Series', isLimited: false},
  {id: 52, rev: 5, mod: 0, name: 'Daihatsu Copen', isLimited: true},
  {id: 52, rev: 5, mod: 1, name: 'Daihatsu Copen', isLimited: false},

  {id: 53, rev: 3, mod: 0, name: 'Nissan Diesel Quon Mixer Car', isLimited: false},

  {id: 54, rev: 5, mod: 0, name: 'City Turbo II', isLimited: false},
  {id: 54, rev: 6, mod: 0, name: 'Honda Prelude', isLimited: false},
  {id: 54, rev: 7, mod: 0, name: 'Range Rover Type', isLimited: false},
  {id: 54, rev: 8, mod: 0, name: 'Subaru Impreza WRX', isLimited: false},
  {id: 54, rev: 9, mod: 0, name: 'Honda Civic Type R', isLimited: false},
  {id: 54, rev: 10, mod: 0, name: 'Honda Civic Type R Euro', isLimited: false},
  {id: 54, rev: 11, mod: 0, name: 'Toyota Town Ace Hamburger Car', isLimited: false},

  {id: 55, rev: 4, mod: 0, name: 'Crown 4Door Sedan', isLimited: false},
  {id: 55, rev: 5, mod: 0, name: 'Toyota Crown', isLimited: false},
  {id: 55, rev: 6, mod: 0, name: 'Toyota Crown Majesta', isLimited: false},
  {id: 55, rev: 7, mod: 0, name: 'Nissan Fairlady Z', isLimited: false},
  {id: 55, rev: 8, mod: 0, name: 'Nissan Fairlady Z', isLimited: false},
  {id: 55, rev: 9, mod: 0, name: 'Nissan Fairlady Z Roadster', isLimited: false},
  {id: 55, rev: 10, mod: 0, name: 'Isuzu Giga Fried Potato Car', isLimited: false},

  {id: 56, rev: 3, mod: 0, name: 'Condoor Bulldozer Carrier', isLimited: false},
  {id: 56, rev: 4, mod: 0, name: 'Hino Bulldozer Carrier', isLimited: false},
  {id: 56, rev: 5, mod: 0, name: 'Komatsu Bulldozer D155 AX-6', isLimited: false},

  {id: 57, rev: 4, mod: 0, name: 'Nissan Diesel Tank Lorry', isLimited: false},
  {id: 57, rev: 5, mod: 0, name: 'Nissan Diesel Quon Tank Lorry', isLimited: false},
  {id: 57, rev: 6, mod: 0, name: 'Eneos Tank Lorry', isLimited: false},
  {id: 57, rev: 7, mod: 0, name: 'Suzuki Carry Mobile Catering Truck', isLimited: true},
  {id: 57, rev: 7, mod: 1, name: 'Suzuki Carry Mobile Catering Truck', isLimited: false},

  {id: 58, rev: 3, mod: 0, name: 'Cedric Patrol Car', isLimited: false},
  {id: 58, rev: 4, mod: 0, name: 'Cedric Patrol Car', isLimited: false},
  {id: 58, rev: 5, mod: 0, name: 'Nissan Cedric Patrol Car', isLimited: false},
  {id: 58, rev: 6, mod: 0, name: 'Suzuki Wagon R', isLimited: false},
  {id: 58, rev: 7, mod: 0, name: 'Suzuki Wagon R', isLimited: false},
  {id: 58, rev: 8, mod: 0, name: 'Daihatsu Wake', isLimited: true},
  {id: 58, rev: 8, mod: 1, name: 'Daihatsu Wake', isLimited: false},

  {id: 59, rev: 3, mod: 0, name: 'Sakai Vibratory Tandem Roller SW 502-1', isLimited: false},
  {id: 59, rev: 4, mod: 0, name: 'Isuzu Elf Sagawa Express', isLimited: false},

  {id: 60, rev: 3, mod: 0, name: 'Toyota Celsior Privately Owned Taxi', isLimited: false},
  {id: 60, rev: 4, mod: 0, name: 'Toyota Mark X Owned Car', isLimited: false},
  {id: 60, rev: 5, mod: 0, name: 'Toyota Corolla Fielder', isLimited: false},
  {id: 60, rev: 6, mod: 0, name: 'Ford Mustang GT V8', isLimited: true},
  {id: 60, rev: 6, mod: 1, name: 'Ford Mustang GT V8', isLimited: false},

  {id: 61, rev: 4, mod: 0, name: 'Toyota Hilux Bigfoot', isLimited: false},
  {id: 61, rev: 5, mod: 0, name: 'Suzuki Swift Sport', isLimited: false},
  {id: 61, rev: 6, mod: 0, name: 'Suzuki Alto', isLimited: false},
  {id: 61, rev: 7, mod: 0, name: 'BMW Z4', isLimited: true},
  {id: 61, rev: 7, mod: 1, name: 'BMW Z4', isLimited: false},

  {id: 62, rev: 4, mod: 0, name: 'Williams Honda F-1', isLimited: false},
  {id: 62, rev: 5, mod: 0, name: 'Daihatsu Midget', isLimited: false},
  {id: 62, rev: 6, mod: 0, name: 'Daihatsu Midget II', isLimited: false},
  {id: 62, rev: 7, mod: 0, name: 'Toyota Harrier', isLimited: false},
  {id: 62, rev: 8, mod: 0, name: 'Mazda Axela Sport', isLimited: false},
  {id: 62, rev: 9, mod: 0, name: 'Mazda Atenza', isLimited: true},
  {id: 62, rev: 9, mod: 1, name: 'Mazda Atenza', isLimited: false},
  {id: 62, rev: 10, mod: 0, name: 'Mazda Atenza Private Taxi', isLimited: false},

  {id: 63, rev: 2, mod: 0, name: 'Maeda Seisakusho Mini Crawler Crane', isLimited: false},

  {id: 64, rev: 3, mod: 0, name: 'Honda S2000', isLimited: false},
  {id: 64, rev: 4, mod: 0, name: 'Toyota Mark X', isLimited: false},
  {id: 64, rev: 5, mod: 0, name: 'Porsche Boxster', isLimited: true},
  {id: 64, rev: 5, mod: 1, name: 'Porsche Boxster', isLimited: false},

  {id: 65, rev: 5, mod: 0, name: 'McDonald\'s Panel Van', isLimited: false},
  {id: 65, rev: 6, mod: 0, name: 'Nissan Diesel Big Thumb', isLimited: false},
  {id: 65, rev: 7, mod: 0, name: 'Hitachi Double Arm Working Machine Astaco', isLimited: false},

  {id: 66, rev: 2, mod: 0, name: 'Fuso Truck Crane', isLimited: false},
  {id: 66, rev: 3, mod: 0, name: 'Yanmar Combine AJ 218', isLimited: false},
  {id: 66, rev: 4, mod: 0, name: 'Honda Fit', isLimited: true},
  {id: 66, rev: 4, mod: 1, name: 'Honda Fit', isLimited: false},

  {id: 67, rev: 5, mod: 0, name: 'Highway Mail Coach', isLimited: false},
  {id: 67, rev: 6, mod: 0, name: 'Subaru Sanbar Mail Coach', isLimited: false},
  {id: 67, rev: 7, mod: 0, name: 'Mitsubishi Lancer Evolution X', isLimited: false},

  {id: 68, rev: 2, mod: 0, name: 'Snorkel Fire Truck', isLimited: false},
  {id: 68, rev: 3, mod: 0, name: 'Post Van', isLimited: false},

  {id: 69, rev: 5, mod: 0, name: 'Mitsubishi Fuso Aquarium Truck', isLimited: false},
  {id: 69, rev: 6, mod: 0, name: 'Aquarium Truck', isLimited: false},

  {id: 70, rev: 3, mod: 0, name: 'Isuzu Elf Aerial Platform', isLimited: false},
  {id: 70, rev: 4, mod: 0, name: 'Toyota Geneo Hybrid', isLimited: false},

  {id: 71, rev: 4, mod: 0, name: 'Nissan Mid-4', isLimited: false},
  {id: 71, rev: 5, mod: 0, name: 'Mitsubishi Minica Toppo', isLimited: false},
  {id: 71, rev: 6, mod: 0, name: 'Suzuki Wagon R', isLimited: false},
  {id: 71, rev: 7, mod: 0, name: 'Suzuki Wagon R RR', isLimited: false},
  {id: 71, rev: 8, mod: 0, name: 'Hitachi Construction Machinery Wheel Loader ZW 220', isLimited: false},

  {id: 72, rev: 2, mod: 0, name: 'Honda Beat', isLimited: false},
  {id: 72, rev: 3, mod: 0, name: 'Mitsubishi Pajero Rally Type', isLimited: false},
  {id: 72, rev: 4, mod: 0, name: 'Toyota Mark X', isLimited: false},
  {id: 72, rev: 5, mod: 0, name: 'Mitsubishi Fuso Aero Star Eco Hybrid', isLimited: false},
  {id: 72, rev: 6, mod: 0, name: 'Hino Selega JR Bus Tohoku Super Komachita', isLimited: false},

  {id: 73, rev: 3, mod: 0, name: 'Tadano Rough Terrain Crane Crevo 600', isLimited: false},
  {id: 73, rev: 4, mod: 0, name: 'Kobelco Rough Terrain Crane Panther-X 250', isLimited: false},

  {id: 74, rev: 4, mod: 0, name: 'Skyline Turbo C', isLimited: false},
  {id: 74, rev: 5, mod: 0, name: 'Mitsubishi Fuso Container Truck', isLimited: false},
  {id: 74, rev: 6, mod: 0, name: 'Rescue Truck III Type', isLimited: false},

  {id: 75, rev: 6, mod: 0, name: 'Caravan Patrol Car', isLimited: false},
  {id: 75, rev: 7, mod: 0, name: 'Smart Fortwo Coupe', isLimited: false},
  {id: 75, rev: 8, mod: 0, name: 'Nissan X-trail', isLimited: false},
  {id: 75, rev: 9, mod: 0, name: 'Znug Design Ouroboros', isLimited: false},
  {id: 75, rev: 10, mod: 0, name: 'Suzuki Hustler', isLimited: true},
  {id: 75, rev: 10, mod: 1, name: 'Suzuki Hustler', isLimited: false},

  {id: 76, rev: 4, mod: 0, name: 'Animal Carrier', isLimited: false},
  {id: 76, rev: 5, mod: 0, name: 'Isuzu Giga Dump Truck', isLimited: false},
  {id: 76, rev: 6, mod: 0, name: 'Honda Civic Type-R', isLimited: true},
  {id: 76, rev: 6, mod: 1, name: 'Honda Civic Type-R', isLimited: false},

  {id: 77, rev: 5, mod: 0, name: 'Canter Wrecker', isLimited: false},
  {id: 77, rev: 6, mod: 0, name: 'Hino Profia', isLimited: false},
  {id: 77, rev: 7, mod: 0, name: 'Hino Profia Nippon Express Truck', isLimited: false},

  {id: 78, rev: 5, mod: 0, name: 'Lotus Honda F-1', isLimited: false},
  {id: 78, rev: 6, mod: 0, name: 'Honda HSX', isLimited: false},
  {id: 78, rev: 7, mod: 0, name: 'Toyota Alphard', isLimited: false},
  {id: 78, rev: 8, mod: 0, name: 'Toyota Alphard', isLimited: false},
  {id: 78, rev: 9, mod: 0, name: 'Subaru Levorg', isLimited: true},
  {id: 78, rev: 9, mod: 1, name: 'Subaru Levorg', isLimited: false},

  {id: 79, rev: 3, mod: 0, name: 'One-man Operated Bus', isLimited: false},
  {id: 79, rev: 4, mod: 0, name: 'Toyota Himedic', isLimited: false},

  {id: 80, rev: 4, mod: 0, name: 'Hitachi Construction Machinery Rubber Crawler Carrier EG 110 R', isLimited: false},
  {id: 80, rev: 5, mod: 0, name: 'C11 1 Steam Locomotive', isLimited: false},
  {id: 80, rev: 6, mod: 0, name: 'Jeep Wrangler', isLimited: true},
  {id: 80, rev: 6, mod: 1, name: 'Jeep Wrangler', isLimited: false},

  {id: 81, rev: 2, mod: 0, name: 'Porsche 930 Turbo', isLimited: false},
  {id: 81, rev: 3, mod: 0, name: 'Honda NSX-R', isLimited: false},
  {id: 81, rev: 4, mod: 0, name: 'Honda CR-Z', isLimited: false},
  {id: 81, rev: 5, mod: 0, name: 'Honda N-One', isLimited: false},

  {id: 82, rev: 2, mod: 0, name: 'Pizza Delivery Bike', isLimited: false},
  {id: 82, rev: 3, mod: 0, name: 'Nissan Stagea', isLimited: false},
  {id: 82, rev: 4, mod: 0, name: 'Toyota Passo', isLimited: true},
  {id: 82, rev: 4, mod: 1, name: 'Toyota Passo', isLimited: false},
  {id: 82, rev: 5, mod: 0, name: 'Suzuki Lapin', isLimited: false},
  {id: 82, rev: 6, mod: 0, name: 'Mazda CX-5', isLimited: true},
  {id: 82, rev: 6, mod: 1, name: 'Mazda CX-5', isLimited: false},
  {id: 82, rev: 7, mod: 0, name: 'Mazda CX-5 Patrol Car', isLimited: false},

  {id: 83, rev: 4, mod: 0, name: 'Isuzu Elf Sagawa – Exp', isLimited: false},
  {id: 83, rev: 5, mod: 0, name: 'Honda Insight Patrol Car', isLimited: false},
  {id: 83, rev: 6, mod: 0, name: 'Yanmar Tractor YT5113', isLimited: false},

  {id: 84, rev: 3, mod: 0, name: 'Nissan Skyline Racing', isLimited: false},
  {id: 84, rev: 4, mod: 0, name: 'Skyline GTR Racing', isLimited: false},
  {id: 84, rev: 5, mod: 0, name: 'Toyota Hilux Surf', isLimited: false},
  {id: 84, rev: 6, mod: 0, name: 'Nissan March Patrol Car', isLimited: false},
  {id: 84, rev: 7, mod: 0, name: 'Honda Freed', isLimited: false},
  {id: 84, rev: 8, mod: 0, name: 'Peugeot RCZ', isLimited: true},
  {id: 84, rev: 8, mod: 1, name: 'Peugeot RCZ', isLimited: false},
  {id: 84, rev: 9, mod: 0, name: 'Toyota Vellfire', isLimited: true},
  {id: 84, rev: 9, mod: 1, name: 'Toyota Vellfire', isLimited: false},

  {id: 85, rev: 2, mod: 0, name: 'Road Construction Truck', isLimited: false},
  {id: 85, rev: 3, mod: 0, name: 'Skyline GT-R Investigation Car', isLimited: false},
  {id: 85, rev: 4, mod: 0, name: 'Mitsubishi Pajero Control Vehicle', isLimited: false},
  {id: 85, rev: 5, mod: 0, name: 'Mitsubishi Pajero', isLimited: false},
  {id: 85, rev: 6, mod: 0, name: 'Toyota FJ Cruiser', isLimited: true},
  {id: 85, rev: 6, mod: 1, name: 'Toyota FJ Cruiser', isLimited: false},

  {id: 86, rev: 2, mod: 0, name: 'Rolls Royce Phantom VI', isLimited: false},
  {id: 86, rev: 3, mod: 0, name: 'Toyota Prius', isLimited: false},
  {id: 86, rev: 4, mod: 0, name: 'Mazda Demio', isLimited: false},
  {id: 86, rev: 5, mod: 0, name: 'Mazda Demio', isLimited: false},
  {id: 86, rev: 6, mod: 0, name: 'Toyota Prius α', isLimited: true},
  {id: 86, rev: 6, mod: 1, name: 'Toyota Prius α', isLimited: false},
  {id: 86, rev: 7, mod: 0, name: 'Honda CR-Z Safety Car', isLimited: false},

  {id: 87, rev: 2, mod: 0, name: 'Mercedes Benz 450SEL', isLimited: false},
  {id: 87, rev: 3, mod: 0, name: 'Estima Ambulance', isLimited: false},
  {id: 87, rev: 4, mod: 0, name: 'Nissan Cedric', isLimited: false},
  {id: 87, rev: 5, mod: 0, name: 'Lamborghini Murcielago', isLimited: true},
  {id: 87, rev: 5, mod: 1, name: 'Lamborghini Murcielago', isLimited: false},
  {id: 87, rev: 6, mod: 0, name: 'Lamborghini Aventador LP 700-4', isLimited: true},
  {id: 87, rev: 6, mod: 1, name: 'Lamborghini Aventador LP 700-4', isLimited: false},
  {id: 87, rev: 7, mod: 0, name: 'Lamborghini Aventador LP 700-4 Dubai Police Car', isLimited: false},

  {id: 88, rev: 2, mod: 0, name: 'BLMC Mini Cooper MK-II', isLimited: false},
  {id: 88, rev: 3, mod: 0, name: 'Toyota Will Cypha', isLimited: true},
  {id: 88, rev: 3, mod: 1, name: 'Toyota Will Cypha', isLimited: false},
  {id: 88, rev: 4, mod: 0, name: 'Mazda MPV', isLimited: false},
  {id: 88, rev: 5, mod: 0, name: 'Nissan Elgrand', isLimited: false},
  {id: 88, rev: 6, mod: 0, name: 'Nissan Elgrand Road Patrol Car', isLimited: false},

  {id: 89, rev: 2, mod: 0, name: 'Porsche 356 Speedster', isLimited: false},
  {id: 89, rev: 3, mod: 0, name: 'Nissan Elgrand', isLimited: false},
  {id: 89, rev: 4, mod: 0, name: 'Toyota Prius', isLimited: false},
  {id: 89, rev: 5, mod: 0, name: 'Suzuki Carry', isLimited: false},

  {id: 90, rev: 2, mod: 0, name: 'Porsche 935-78 Turbo', isLimited: false},
  {id: 90, rev: 3, mod: 0, name: 'Soarer Patrol Car', isLimited: false},
  {id: 90, rev: 4, mod: 0, name: 'Isuzu Fruit Shop Van', isLimited: false},
  {id: 90, rev: 5, mod: 0, name: 'Suzuki Carry', isLimited: false},
  {id: 90, rev: 6, mod: 0, name: 'Tentmushi', isLimited: false},
  {id: 90, rev: 7, mod: 0, name: 'Fiat 500', isLimited: true},
  {id: 90, rev: 7, mod: 1, name: 'Fiat 500', isLimited: false},
  {id: 90, rev: 8, mod: 0, name: 'UD Trucks Quon ENEOS Tank Lorry', isLimited: false},

  {id: 91, rev: 2, mod: 0, name: 'Ferrari Testarossa', isLimited: false},
  {id: 91, rev: 3, mod: 0, name: 'Porsche Boxster', isLimited: false},
  {id: 91, rev: 4, mod: 0, name: 'Mercedes Benz SLS AMG', isLimited: false},

  {id: 92, rev: 2, mod: 0, name: 'Lamborghini Countach LP500S', isLimited: false},
  {id: 92, rev: 3, mod: 0, name: 'Mercedes-Benz C Class Type', isLimited: false},
  {id: 92, rev: 4, mod: 0, name: 'Toyota Crown Hybrid', isLimited: false},
  {id: 92, rev: 5, mod: 0, name: 'Toyota Coaster', isLimited: false},
  {id: 92, rev: 6, mod: 0, name: 'Toyota Ractis', isLimited: false},
  {id: 92, rev: 7, mod: 0, name: 'Toyota Crown Athlete', isLimited: false},

  {id: 93, rev: 2, mod: 0, name: 'Mitsubishi Fuso Racing Transporter', isLimited: false},
  {id: 93, rev: 3, mod: 0, name: 'Quick Delivery Van', isLimited: false},
  {id: 93, rev: 4, mod: 0, name: 'My Melody Bus', isLimited: false},
  {id: 93, rev: 5, mod: 0, name: 'Mitsubishi Fuso Aero Star', isLimited: false},
  {id: 93, rev: 6, mod: 0, name: 'Toyota Wish', isLimited: false},
  {id: 93, rev: 7, mod: 0, name: 'Toyota Camry', isLimited: false},
  {id: 93, rev: 8, mod: 0, name: 'Mitsubishi Triton JAF Road Service Car', isLimited: false},

  {id: 94, rev: 3, mod: 0, name: 'Jaguar XJ-S Group A', isLimited: false},
  {id: 94, rev: 4, mod: 0, name: 'Minica Toppo Florist\'s Van', isLimited: false},
  {id: 94, rev: 5, mod: 0, name: 'Mazda RX-7', isLimited: false},
  {id: 94, rev: 6, mod: 0, name: 'Nissan GT-R', isLimited: false},

  {id: 95, rev: 3, mod: 0, name: 'London Bus (Pet World)', isLimited: false},

  {id: 96, rev: 3, mod: 0, name: 'Subaru Sumber Milk Delivery Van', isLimited: false},
  {id: 96, rev: 4, mod: 0, name: 'Toyota Celica', isLimited: false},
  {id: 96, rev: 5, mod: 0, name: 'Mazda RX-8', isLimited: false},
  {id: 96, rev: 6, mod: 0, name: 'Yamaha YFZ 450 R', isLimited: false},
  {id: 96, rev: 7, mod: 0, name: 'Honda Step-wagon', isLimited: true},
  {id: 96, rev: 7, mod: 1, name: 'Honda Step-wagon', isLimited: false},

  {id: 97, rev: 3, mod: 0, name: 'Citroen H Truck', isLimited: false},
  {id: 97, rev: 4, mod: 0, name: 'Shinkansen Trailer', isLimited: false},
  {id: 97, rev: 5, mod: 0, name: 'Toyota Probox', isLimited: false},
  {id: 97, rev: 6, mod: 0, name: 'Toyota Town Ace', isLimited: false},
  {id: 97, rev: 7, mod: 0, name: 'Doctor Heli', isLimited: false},

  {id: 98, rev: 2, mod: 0, name: 'American Mixer', isLimited: false},
  {id: 98, rev: 3, mod: 0, name: 'Isuzu Elf Panel Truck', isLimited: false},
  {id: 98, rev: 4, mod: 0, name: 'Toyota Celica Racing Type', isLimited: false},
  {id: 98, rev: 5, mod: 0, name: 'Toyota Noah', isLimited: false},
  {id: 98, rev: 6, mod: 0, name: 'Toyota Avensis', isLimited: false},
  {id: 98, rev: 7, mod: 0, name: 'Toyota Aqua', isLimited: true},
  {id: 98, rev: 7, mod: 1, name: 'Toyota Aqua', isLimited: false},
  {id: 98, rev: 8, mod: 0, name: 'Spyker C8 Laviolette SWB', isLimited: true},
  {id: 98, rev: 8, mod: 1, name: 'Spyker C8 Laviolette SWB', isLimited: false},
  {id: 98, rev: 9, mod: 0, name: 'Honda S660', isLimited: true},
  {id: 98, rev: 9, mod: 1, name: 'Honda S660', isLimited: false},

  {id: 99, rev: 3, mod: 0, name: 'Mercedes Benz 300SL', isLimited: false},
  {id: 99, rev: 4, mod: 0, name: 'Toyota Estima', isLimited: false},
  {id: 99, rev: 5, mod: 0, name: 'Toyota Estima', isLimited: false},
  {id: 99, rev: 6, mod: 0, name: 'Toyota Estima', isLimited: false},
  {id: 99, rev: 7, mod: 0, name: 'Nissan Serena', isLimited: false},
  {id: 99, rev: 8, mod: 0, name: 'Toyota Sienta', isLimited: false},

  {id: 100, rev: 2, mod: 0, name: 'Volkswagen 1200LSE', isLimited: false},
  {id: 100, rev: 3, mod: 0, name: 'Honda Fit', isLimited: false},
  {id: 100, rev: 4, mod: 0, name: 'Honda Fit', isLimited: false},
  {id: 100, rev: 5, mod: 0, name: 'Honda Fit Shuttle', isLimited: false},
  {id: 100, rev: 6, mod: 0, name: 'Lexus IS 350 F Sports', isLimited: true},
  {id: 100, rev: 6, mod: 1, name: 'Lexus IS 350 F Sports', isLimited: false},

  {id: 101, rev: 2, mod: 0, name: 'McLaren F-1', isLimited: false},
  {id: 101, rev: 3, mod: 0, name: 'JR High-way Truck', isLimited: false},
  {id: 101, rev: 4, mod: 0, name: 'Honda Odyssey Wagon Taxi', isLimited: false},
  {id: 101, rev: 5, mod: 0, name: 'Hino S\'Elega', isLimited: false},

  {id: 102, rev: 2, mod: 0, name: 'Off Road Dump', isLimited: false},
  {id: 102, rev: 3, mod: 0, name: 'Hitachi Rigid Dump Truck EH 3500 AC II', isLimited: false},

  {id: 103, rev: 2, mod: 0, name: 'BMW 320i', isLimited: false},
  {id: 103, rev: 3, mod: 0, name: 'Komatsu Mini Power Shuffle PC45', isLimited: false},
  {id: 103, rev: 4, mod: 0, name: 'Pikachu Car', isLimited: false},
  {id: 103, rev: 5, mod: 0, name: 'Nissan Note', isLimited: false},
  {id: 103, rev: 6, mod: 0, name: 'Toyota Land Cruiser', isLimited: false},

  {id: 104, rev: 2, mod: 0, name: 'Nissan Cima', isLimited: false},
  {id: 104, rev: 3, mod: 0, name: 'Mitsubishi Lancer Evo IV WRC', isLimited: false},
  {id: 104, rev: 4, mod: 0, name: 'Suzuki Skywave', isLimited: false},
  {id: 104, rev: 5, mod: 0, name: 'Toyota Vitz', isLimited: true},
  {id: 104, rev: 5, mod: 1, name: 'Toyota Vitz', isLimited: false},
  {id: 104, rev: 6, mod: 0, name: 'Lotus Evora GTE', isLimited: true},
  {id: 104, rev: 6, mod: 1, name: 'Lotus Evora GTE', isLimited: false},

  {id: 105, rev: 2, mod: 0, name: 'Tire Roller', isLimited: false},
  {id: 105, rev: 3, mod: 0, name: 'Coca-Cola Route Truck', isLimited: false},
  {id: 105, rev: 4, mod: 0, name: 'Coca-Cola Route Truck', isLimited: false},
  {id: 105, rev: 5, mod: 0, name: 'Coca-Cola Route Truck', isLimited: false},
  {id: 105, rev: 6, mod: 0, name: 'Suzuki MR Wagon', isLimited: true},
  {id: 105, rev: 6, mod: 1, name: 'Suzuki MR Wagon', isLimited: false},
  {id: 105, rev: 7, mod: 0, name: 'Skyline', isLimited: true},
  {id: 105, rev: 7, mod: 1, name: 'Skyline', isLimited: false},
  {id: 105, rev: 8, mod: 0, name: 'Nissan NV350 Caravan', isLimited: true},
  {id: 105, rev: 8, mod: 1, name: 'Nissan NV350 Caravan', isLimited: false},

  {id: 106, rev: 2, mod: 0, name: 'Porsche 959 Patrol Car', isLimited: false},
  {id: 106, rev: 3, mod: 0, name: 'Mitsubishi Pajero Patrol Car', isLimited: false},
  {id: 106, rev: 4, mod: 0, name: 'Toyota Prius', isLimited: false},
  {id: 106, rev: 5, mod: 0, name: 'Nissan Fairlady Z Patrol Car', isLimited: false},
  {id: 106, rev: 6, mod: 0, name: 'Komatsu Towbarless Tractor WZ 4000', isLimited: false},
  {id: 106, rev: 7, mod: 0, name: 'Tommykaira ZZ', isLimited: true},
  {id: 106, rev: 7, mod: 1, name: 'Tommykaira ZZ', isLimited: false},

  {id: 107, rev: 2, mod: 0, name: 'Ford Cattle Truck', isLimited: false},
  {id: 107, rev: 3, mod: 0, name: 'Road Service Car', isLimited: false},
  {id: 107, rev: 4, mod: 0, name: 'Mercedes-Benz A Class', isLimited: false},
  {id: 107, rev: 5, mod: 0, name: 'Honda Element', isLimited: false},
  {id: 107, rev: 6, mod: 0, name: 'Toyota Voxy', isLimited: false},
  {id: 107, rev: 7, mod: 0, name: 'Lexus IS F CCS-R', isLimited: false},

  {id: 108, rev: 2, mod: 0, name: 'Hilux Camper Car', isLimited: false},
  {id: 108, rev: 3, mod: 0, name: 'Mitsubishi Fuso Animal Carrier', isLimited: false},
  {id: 108, rev: 4, mod: 0, name: 'Hino Aerial Ladder Fire Truck', isLimited: false},

  {id: 109, rev: 1, mod: 0, name: 'Nissan Bluebird Taxi', isLimited: false},
  {id: 109, rev: 2, mod: 0, name: 'Bireley\'s Event Car', isLimited: false},
  {id: 109, rev: 3, mod: 0, name: 'Toyota Crown Athlete', isLimited: false},
  {id: 109, rev: 4, mod: 0, name: 'Nissan Serena', isLimited: false},
  {id: 109, rev: 5, mod: 0, name: 'Mitsubishi Triton', isLimited: false},
  {id: 109, rev: 6, mod: 0, name: 'Volkswagen Polo', isLimited: true},
  {id: 109, rev: 6, mod: 1, name: 'Volkswagen Polo', isLimited: false},
  {id: 109, rev: 7, mod: 0, name: 'Volkswagen Polo Patrol Car', isLimited: false},

  {id: 110, rev: 2, mod: 0, name: 'Nissan Diesel Pump Fire Engine', isLimited: false},
  {id: 110, rev: 3, mod: 0, name: 'Toyota Vitz', isLimited: false},
  {id: 110, rev: 4, mod: 0, name: 'Toyota Crown Patrol Car', isLimited: false},
  {id: 110, rev: 5, mod: 0, name: 'Toyota Crown Patrol Car', isLimited: true},
  {id: 110, rev: 5, mod: 1, name: 'Toyota Crown Patrol Car', isLimited: false},

  {id: 111, rev: 2, mod: 0, name: 'Eunos Roadster', isLimited: false},
  {id: 111, rev: 3, mod: 0, name: 'Honda CR-V', isLimited: false},
  {id: 111, rev: 4, mod: 0, name: 'Subaru R1', isLimited: true},
  {id: 111, rev: 4, mod: 1, name: 'Subaru R1', isLimited: false},
  {id: 111, rev: 5, mod: 0, name: 'Nissan Skyline Crossover', isLimited: false},
  {id: 111, rev: 6, mod: 0, name: 'Audi A1', isLimited: true},
  {id: 111, rev: 6, mod: 1, name: 'Audi A1', isLimited: false},

  {id: 112, rev: 1, mod: 0, name: 'Isuzu Elf Bottle Car', isLimited: false},
  {id: 112, rev: 2, mod: 0, name: 'Mitsubishi Pajero Jr.', isLimited: false},
  {id: 112, rev: 3, mod: 0, name: 'High-way Public Co. Patrol Car', isLimited: false},
  {id: 112, rev: 4, mod: 0, name: 'Honda Airwave', isLimited: false},
  {id: 112, rev: 4, mod: 0, name: 'Subaru Legacy B4', isLimited: false},
  {id: 112, rev: 5, mod: 0, name: 'Subaru Forester', isLimited: true},
  {id: 112, rev: 5, mod: 1, name: 'Subaru Forester', isLimited: false},
  {id: 112, rev: 6, mod: 0, name: 'Subaru WRX STi Type S', isLimited: true},
  {id: 112, rev: 6, mod: 1, name: 'Subaru WRX STi Type S', isLimited: false},

  {id: 113, rev: 1, mod: 0, name: 'Mechanical Sweeper', isLimited: false},
  {id: 113, rev: 2, mod: 0, name: 'Nissan Skyline', isLimited: false},
  {id: 113, rev: 3, mod: 0, name: 'Mechanical Sweeper', isLimited: false},
  {id: 113, rev: 4, mod: 0, name: 'Lamborghini Reventon', isLimited: true},
  {id: 113, rev: 4, mod: 1, name: 'Lamborghini Reventon', isLimited: false},

  {id: 114, rev: 1, mod: 0, name: 'Chevrolet Camaro Police Car', isLimited: false},
  {id: 114, rev: 2, mod: 0, name: 'Komatsu Bulldozer D375A', isLimited: false},
  {id: 114, rev: 3, mod: 0, name: 'JSDF Light Armoured Vehicle', isLimited: false},

  {id: 115, rev: 1, mod: 0, name: 'Toyota Crown Taxi', isLimited: false},
  {id: 115, rev: 2, mod: 0, name: 'Crown Majesta Taxi', isLimited: false},
  {id: 115, rev: 3, mod: 0, name: 'Mazda Roadster', isLimited: false},
  {id: 115, rev: 4, mod: 0, name: 'Bentley Continential GT', isLimited: false},
  {id: 115, rev: 5, mod: 0, name: 'Suzuki Carry Mobile Shop', isLimited: true},
  {id: 115, rev: 5, mod: 1, name: 'Suzuki Carry Mobile Shop', isLimited: false},
  {id: 115, rev: 6, mod: 0, name: 'Toyota Voxy', isLimited: true},
  {id: 115, rev: 6, mod: 1, name: 'Toyota Voxy', isLimited: false},

  {id: 116, rev: 1, mod: 0, name: 'Porsche 956', isLimited: false},
  {id: 116, rev: 2, mod: 0, name: 'Super Ambulance', isLimited: false},
  {id: 116, rev: 3, mod: 0, name: 'Super Ambulance', isLimited: false},

  {id: 117, rev: 1, mod: 0, name: 'Neoplan Bus Skyliner', isLimited: false},
  {id: 117, rev: 2, mod: 0, name: 'Ferrari F-1', isLimited: false},
  {id: 117, rev: 3, mod: 0, name: 'Mazda RX-7 Patrol Car', isLimited: false},
  {id: 117, rev: 4, mod: 0, name: 'Mitsubishi i', isLimited: false},
  {id: 117, rev: 5, mod: 0, name: 'Mitsubishi i-Miev', isLimited: false},
  {id: 117, rev: 6, mod: 0, name: 'Porsche 911 Carrera', isLimited: true},
  {id: 117, rev: 6, mod: 1, name: 'Porsche 911 Carrera', isLimited: false},

  {id: 118, rev: 1, mod: 0, name: 'Terex 72-81 Loader', isLimited: false},
  {id: 118, rev: 2, mod: 0, name: 'Toyota Coaster Kindergarten Bus', isLimited: false},
  {id: 118, rev: 3, mod: 0, name: 'Honda CR-V', isLimited: true},
  {id: 118, rev: 3, mod: 1, name: 'Honda CR-V', isLimited: false},
  {id: 118, rev: 4, mod: 0, name: 'Lamborghini Veneno', isLimited: true},
  {id: 118, rev: 4, mod: 1, name: 'Lamborghini Veneno', isLimited: false},

  {id: 119, rev: 1, mod: 0, name: 'Ferrari BB 512', isLimited: false},
  {id: 119, rev: 2, mod: 0, name: 'Hiace Fire Chief Car', isLimited: false},
  {id: 119, rev: 3, mod: 0, name: 'Care Support Car', isLimited: false},
  {id: 119, rev: 4, mod: 0, name: 'Morita Fire Fighting Ambulance', isLimited: false},

  {id: 120, rev: 1, mod: 0, name: 'Porsche 959', isLimited: false},
  {id: 120, rev: 2, mod: 0, name: 'Footwork F-1', isLimited: false},
  {id: 120, rev: 3, mod: 0, name: 'Honda NSX Patrol Car', isLimited: false},
  {id: 120, rev: 4, mod: 0, name: 'Komatsu Articulated Dump Truck', isLimited: false},
  {id: 120, rev: 5, mod: 0, name: 'Nissan Leaf', isLimited: true},
  {id: 120, rev: 5, mod: 1, name: 'Nissan Leaf', isLimited: false},
  {id: 120, rev: 6, mod: 0, name: 'Subaru BRZ', isLimited: false}
]
